#ifndef ARDUINOOSC_H
#define ARDUINOOSC_H

#include "ArduinoOSCWiFi.h"
#include "ArduinoOSCEther.h"

#if !defined(ARDUINOOSC_ENABLE_WIFI) && !defined(ARDUINOOSC_ENABLE_ETHER)
#error THIS PLATFORM HAS NO WIFI OR ETHERNET OR NOT SUPPORTED ARCHITECTURE. PLEASE LET ME KNOW!
#endif

#if defined(ARDUINOOSC_ENABLE_WIFI) && defined(ARDUINOOSC_ENABLE_ETHER)
#error BOTH WIFI AND ETHERNET ARE ENABLED. PLEASE INCLUDE ONLY ArduinoOSCWiFi.h OR ArduinoOSCEther.h
#endif

#endif  // ARDUINOOSC_H
